<SettingScreen@MDScreen>:
    name: "setting"

    MDBoxLayout:
        orientation: "vertical"
        padding: dp(24)
        spacing: dp(24)
        size_hint_y: None
        height: self.minimum_height
        pos_hint: {"top": 1}

        FMTitle:
            use_logo: True
            title: "Settings"
            title_style: "H5"
            subtitle_style: "Body1"

    FMNavigation:
        id: navigation
        size_hint_x: 1